name: Find All Folders

on:
  workflow_dispatch

jobs:

  prepare_matrix:
    runs-on: ubuntu-latest
    
    outputs:
      folders: ${{ steps.get_folders.outputs.folder_names_json }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get folder names and format as JSON array
        id: get_folders
        run: |
          FOLDER_NAMES_JSON=$(find Python -mindepth 1 -maxdepth 1 -type d -print0 | xargs -0 -I {} basename "{}" | jq -R -s -c 'split("\n")[:-1]')

          echo "Found folders (JSON): $FOLDER_NAMES_JSON"

          echo "folder_names_json=$FOLDER_NAMES_JSON" >> "$GITHUB_OUTPUT"


  process_folders:
    needs: prepare_matrix
    runs-on: ubuntu-latest
    permissions:
      packages: write
      
    strategy:
      matrix:
        version: ${{ fromJson(needs.prepare_matrix.outputs.folders) }}
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for Python ${{ matrix.version }}
        uses: docker/build-push-action@v5
        with:
          context: ./Python/
          file: ./Python/${{ matrix.version }}/Dockerfile
          push: true
          tags: ghcr.io/yoloftw/python:${{ matrix.version }}
          
